// Generated by https://quicktype.io

export interface RegisterResponse {
    id:              string;
    username:        string;
    email:           string;
    telefono:        string;
    avatar:          string;
    perfil:          string;
    fecha:           string;
    posts:           any[];
    listaPeticiones: any[];
    followers:       any[];
}
